### ISSUE TITLE
Support for AEG-PX71-265WT 

### ISSUE THREAD

**Issue by DJay-X** [karlg100/homebridge-frigidaire#12]
@karlg100 Thanks for your work and sharing.
I was happy to have found your plugin by chance. 
I recently purchased here in Germany a [AEG-PX71-265WT](https://www.aeg.de/vacuums-home-comfort/air-comfort/air-conditioners/portable-air-conditioner/px71-265wt/) which should be identical to the [Frigidaire Gallery](https://www.frigidaire.com/Home-Comfort/Air-Conditioning/Portable-Air-Conditioners/FGPC1244TE/)

Unfortunately the plugin did not work with the AEG at the moment. But worth a try. ;) 
Any chance you could modify the the plugin so that AEG Users also take advantage of your great plugin. As far as it is possible for me, I am of course happy to help.
Very appreciate your time you put in this.
Thanks in advance. 👍 

```
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]: [2019-6-24 15:07:35] TypeError: Cannot read property 'attributes' of undefined
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at /usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:436:58
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at Request._callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:282:14)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at Request.self.callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at Request.emit (events.js:193:13)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1161:10)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at Request.emit (events.js:193:13)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1083:12)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at Object.onceWrapper (events.js:281:20)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at IncomingMessage.emit (events.js:198:15)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at endReadableNT (_stream_readable.js:1139:12)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)
Jun 24 15:07:35 raspberrypi-3BPlus homebridge[26248]: [2019-6-24 15:07:35] Got SIGTERM, shutting down Homebridge...
Jun 24 15:07:37 raspberrypi-3BPlus homebridge[26248]: [2019-6-24 15:07:37] [Config] Console v4.5.1 is listening on :: port 8082
Jun 24 15:07:40 raspberrypi-3BPlus systemd[1]: homebridge-2nd-Instance.service: Main process exited, code=exited, status=143/n/a
Jun 24 15:07:40 raspberrypi-3BPlus systemd[1]: homebridge-2nd-Instance.service: Unit entered failed state.
Jun 24 15:07:40 raspberrypi-3BPlus systemd[1]: homebridge-2nd-Instance.service: Failed with result 'exit-code'.
```

**Comment by karlg100** [comment]
Check to see if the app in the US App Store is the same as in the Germany App Store on your phone.  (Can you download the US app, sign in with the US version and control your AC unit?)

If so, then may just be attributes that need to be remapped in the underlying Frigidaire node library for your model.

Otherwise, (and my bet) it may be a different server for Germany.  To resolve this, you’ll need to MITM the app on your device and look at where it’s connecting.

Karlg100

**Comment by DJay-X** [comment]
Thanks. I downloaded the Frigidaire App and created a new Account. It's a different Server.
But I was not able to connect the AC to WiFi. WiFi Setup process is different to the German AEG Home Comfort App. But I got around this and managed to the last step to connect to my home WiFi. Unfortunately the App or AC was not able to connect to my WiFi. Maybe Country differences?
The best way will probably to try to find your what the AEG App is doing by using MITM. But I have no idea how to do this on macOS and what I should look for. Probably using Charles App or so.

**Comment by DJay-X** [comment]
@karlg100 Hi again. I was able to configure Charles Proxy on my iMac and route the traffic from the iPhone to Charles.
But now I need your help what I should look for or what is helpful to you.
When I used the AEG App and switched the AC on/off and Temp, I noticed some traffic going to 
https://e408cc7134770d9672d2feab04700812bizappmanage.ibroadlink.com
https://e408cc7134770d9672d2feab04700812bizihcv0.ibroadlink.com
https://e408cc7134770d9672d2feab04700812bizappdata.ibroadlink.com

But I have no idea what I should look for and how. Hope you can help.
I appreciate the time you are investing and considering to implement AEG AC support.
Thanks again.

**Comment by karlg100** [comment]
You’ll need to inspect the HTTP traffic.  The only way to do this is install your own Self signed CA certificate on your device (and trust it) then route traffic thru a proxy that can decrypt the packets.  Never use Charles proxy so no idea if that will work or not.  Mitmproxy makes this pretty easy to inspect traffic.  This can be done on a Linux system like a digital ocean droplet.

Karl Grindley

**Comment by DJay-X** [comment]
Thanks @karlg100 . Unfortunately, however, this exceeds my knowledge and skills. But I will point out your project to some people in the German Homebridge Forum. Maybe there are experts. 
Too bad that I can't provide more information here. To control the air conditioning directly via HomeKit/Homebridge would be a dream.
Anyway, thanks to you for the moment.

**Comment by karlg100** [comment]
here's a short article I had written a while back.
https://thekag.postach.io/post/setting-up-mitmproxy-to-inspect-app-traffic

you can try that.  then inspect the traffic in the mitmproxy console.  you're looking for server name compared to the US version (https://prod2.connappl.com/ELXBasic)

**Comment by DJay-X** [comment]
@karlg100 Thanks to your short article I was able to run mitmproxy creating a DigitalOcean account and so on...
WOW.. what I have learned in the last 2 hours. Or not. ;) 
Anyway I got some output in mitbroxy when I open the AEG App and control the AC.
But I'm not sure what is helpful and/or save to post here.
I found some urls like the following.
Hope this helps and you can make something out of it.
Please of course let me know if there is anything from my side that I can do, now that I have mitmproxy up.

Thanks again for the time you are investing and for trying to get this to work.

https://eluxota.ibroadlink.com/v1/account/istester
Host:             eluxota.ibroadlink.com 
POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo
User-Agent:       NewElectrolux/20190129 CFNetwork/978.0.7 Darwin/18.6.0
Host:             gspe1-ssl.ls.apple.com



[NUMBERTHATSAYSLICENSEID] is something linke a123bb7654321b4321b1gbed12345678bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo

```
>> GET https://gspe1-ssl.ls.apple.com/pep/gcc                                                                                                                  
       ← 200 text/html 2b 45ms                                                                                                                                 
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/user/getfamilyid                                                                
        ← 200 text/plain 169b 65ms                                                                                                                             
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo                                                               
        ← 200 text/plain 4.16k 86ms                                                                                                                            
   POST https://[NUMBERTHATSAYSLICENSEID]bizappmanage.ibroadlink.com/ec4/v1/system/getresourceversionbypid                                              
        ← 200 text/plain 150b 680ms                                                                                                                            
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/user/getfamilyid                                                                
        ← 200 text/plain 169b 64ms                                                                                                                             
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo                                                               
        ← 200 text/plain 4.16k 87ms                                                                                                                            
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/user/getfamilyid                                                                
        ← 200 text/plain 169b 69ms                                                                                                                             
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo                                                               
        ← 200 text/plain 4.16k 92ms                                                                                                                            
   POST https://eluxota.ibroadlink.com/v1/account/istester                                                                                                     
        ← 200 application/json 48b 73ms                                                                                                                        
   POST https://[NUMBERTHATSAYSLICENSEID]bizappdata.ibroadlink.com/data/v1/appdata/upload?source=app&datatype=app_user_v1                               
        ← 200 text/plain 21b 55ms                                                                                                                              
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/user/getfamilyid                                                                
        ← 200 text/plain 169b 72ms                                                                                                                             
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo                                                               
        ← 200 text/plain 4.16k 88ms                                                                                                                            
   POST https://[NUMBERTHATSAYSLICENSEID]bizappmanage.ibroadlink.com/ec4/v1/system/getresourceversionbypid                                              
        ← 200 text/plain 150b 638ms                                                                                                                            
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/user/getfamilyid                                                                
        ← 200 text/plain 169b 76ms                                                                                                                             
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo                                                               
        ← 200 text/plain 4.16k 94ms                                                                                                                            
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/user/getfamilyid                                                                
        ← 200 text/plain 169b 64ms                                                                                                                             
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo                                                               
        ← 200 text/plain 4.16k 97ms                                                                                                                            
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/user/getfamilyid                                                                
        ← 200 text/plain 169b 65ms                                                                                                                             
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo                                                               
        ← 200 text/plain 4.16k 90ms                                                                                                                            
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/user/getfamilyid                                                                
        ← 200 text/plain 169b 67ms                                                                                                                             
   POST https://[NUMBERTHATSAYSLICENSEID]bizihcv0.ibroadlink.com/ec4/v1/family/getallinfo                                                               
        ← 200 text/plain 4.16k 100ms                                                                                                                           
   POST https://eluxota.ibroadlink.com/v1/account/istester                                                                                                     
        ← 200 application/json 48b 63ms           
```                      

```
2019-07-16 16:59:50 POST https://a123bb7654321b4321b1gbed12345678bizappdata.ibroadlink.com/data/v1/appdata/upload?source=app&datatype=app_user_v1              
                         ← 200 OK text/plain 21b 55ms                                                                                                          
                       Request                                              Response                                              Detail                       
Host:              a123bb7654321b4321b1gbed12345678bizappdata.ibroadlink.com                                                                                   
Content-Type:      application/octet-stream                                                                                                                    
User-Agent:        NewElectrolux/20190129 CFNetwork/978.0.7 Darwin/18.6.0                                                                                      
Connection:        keep-alive                                                                                                                                  
Signature:         a123bb7654321b4321b1gbed12345678                                                                                                            
Accept:            */*                                                                                                                                         
Content-Encoding:  gzip                                                                                                                                        
Accept-Language:   de-de                                                                                                                                       
Timestamp:         1563296389                                                                                                                                  
Content-Length:    621                                                                                                                                         
Accept-Encoding:   br, gzip, deflate                                                                                                                           
[decoded gzip] Query                                                                                                                                   [m:auto]
source:   app                                                                                                                                                  
datatype: app_user_v1
```

**Comment by DJay-X** [comment]
I close this, because I was all-in-all not happy with this aircon and returned it. So no investment of time is needed anymore. Thanks again.

**Comment by endocrimes** [comment]
We just got one of these - tempted to hack on adding support this weekend because their 1st party app is uhh... subpar.

**Comment by zonksoft** [comment]
Hi everyone! I have one and don't plan to return it. What's the status? I'm happy to contribute!

**Comment by karlg100** [comment]
Use home assistant and the HACS plugin.  Very widely used and well maintained

**Comment by zonksoft** [comment]
I will, thank you so much!
