### ISSUE TITLE
Better login error handling

### ISSUE THREAD

**Issue by amaisano** [karlg100/homebridge-frigidaire#18]
I recently changed my password but since Homebridge was already running nothing happened and things were fine. However, today I restarted my homebridge server and was given this error:

```
[8/7/2019, 12:50:44 PM] TypeError: Cannot read property 'attributes' of undefined
    at /usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:439:58
    at Request._callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:285:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Turns out I needed to update my password in my config.json file, but the error above gives me zero hint that this was the problem. Is there a way to make this clearer, like "Error: bad login credentials / could not login"?

**Comment by alfista2600** [comment]
I've simplified my password several times to no avail. My email is.  xxx@yyy.zzz.com, however. What else can this be?

**Comment by amaisano** [comment]
Just throwing this out there - is there a parsing problem with multiple subdomains in the email address? Have you tried an email with a single host domain (xxx@yyy.com)?

**Comment by alfista2600** [comment]
Yeah, that is why I included it in my post. I assumed it would use a 'standard' library but who knows... I guess I'll have to create another account and reregister the device to test :-(

**Comment by karlg100** [comment]
Please test with 2.0.0 release and let us know if that works better regarding this issue.

**Comment by alfista2600** [comment]
Seems to be working great! Thanks!
Somewhat unrelated question, but how do I find out what commands are possible for a device, so I can use the swagger API to send them?

**Comment by karlg100** [comment]
refer to the support nodeJS module. https://github.com/karlg100/frigidaire

use the `demo.js` to experiment with commands.  You can also reuse this module in other non-homebridge nodeJS projects.
