### ISSUE TITLE
Crash: SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by amaisano** [karlg100/homebridge-frigidaire#28]
```
[6/5/2021, 3:03:47 PM] SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:236:42)
    at self.callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[6/5/2021, 3:03:47 PM] Got SIGTERM, shutting down Homebridge...
```

Then Homebridge crashes and restarts. This usually happens after I set a temperature (Celsius).

**Comment by karlg100** [comment]
Tracking here https://github.com/karlg100/frigidaire/issues/7
