### ISSUE TITLE
This plugin generated a warning from the characteristic 'Filter Change Indication': 

### ISSUE THREAD

**Issue by evanbt** [karlg100/homebridge-frigidaire#44]
I am having two issues with this plug-in and I think they could be related. 

On start-up I am getting this error.

`This plugin generated a warning from the characteristic 'Filter Change Indication': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
`
After about 24 hours of running, the device stops responding in HomeKit and I get this error.

`This plugin slows down Homebridge. The read handler for the characteristic 'Filter Change Indication' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
`

[9/12/2022, 7:30:25 PM] [Frigidaire] Launched child bridge with PID 9966
[9/12/2022, 7:30:26 PM] Registering platform 'homebridge-frigidaire.Frigidaire'
[9/12/2022, 7:30:26 PM] [Frigidaire] Loaded homebridge-frigidaire v2.1.3 child bridge successfully
craeting accessory for AC unit labeled : My RAC 71656752
[9/12/2022, 7:30:27 PM] Initializing platform accessory 'My RAC 71656752'...
[9/12/2022, 7:30:27 PM] Publishing bridge accessory (name: Frigidaire, publishInfo: {
  username: '**:**:**:**:**',
  port: *****,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
[9/12/2022, 7:30:27 PM] Homebridge v1.5.0 (HAP v0.10.2) (Frigidaire) is running on port 45848.
[9/12/2022, 7:30:28 PM] [homebridge-frigidaire] Characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://homebridge.io/w/JtMGR for more info.
[9/12/2022, 7:30:28 PM] [homebridge-frigidaire] Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1756:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at FrigidaireAirConditionerAccessory.setCleanAir (/usr/local/lib/node_modules/homebridge-frigidaire/index.js:198:14)
    at On.emit (node:events:513:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1725:16
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1723:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
[9/12/2022, 7:30:28 PM] [homebridge-frigidaire] This plugin generated a warning from the characteristic 'Filter Change Indication': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[9/12/2022, 7:30:28 PM] [homebridge-frigidaire] Error: 
    at FilterChangeIndication.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at FilterChangeIndication.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2030:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1617:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at /usr/local/lib/node_modules/homebridge-frigidaire/index.js:431:14
    at /usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:1004:17
    at Frigidaire.getValue (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:765:13)
    at Frigidaire.getFilter (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:1000:11)
    at FrigidaireAirConditionerAccessory.getFilter (/usr/local/lib/node_modules/homebridge-frigidaire/index.js:416:13)
    at FilterChangeIndication.emit (node:events:513:28)

**Comment by iJC1976** [comment]
I’m having the same issues. I tried rolling back to the previous release but I’m still getting the “plugin slows down homebridge” error.
