### ISSUE TITLE
403 Forbidden back again

### ISSUE THREAD

**Issue by ntableman** [karlg100/homebridge-frigidaire#7]
Tried the fix in the prior issue, didn't work...

removed and reinstalled the plugin/libs, nope

Error: 403 Forbidden
    at Request._callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:267:15)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by royale56** [comment]
Receiving this same error

**Comment by danielschwartz** [comment]
Seeing this as well

**Comment by danielschwartz** [comment]
I tried manually updating the `useragent` and `version` to `4.0.4` in the `frigidaire` package in `node_modules` and that didn't fix it (based off the last commit in that repo). Will leave it up to @karlg100 to figure out what's going on

**Comment by bwoodruff** [comment]
Something broke... not sure if it is this same error but the symptoms I'm having are all homebridge devices went unresponsive in the Home app until I removed the frigidaire module.

**Comment by karlg100** [comment]
my guess is they've invalidated the deviceID that was hardcoded in the support lib.

I'm working to get my test environment set back up so I can scrape a new device ID.

**Comment by danielschwartz** [comment]
@karlg100 can you get the deviceId/clientId by sniffing requests using Charles? If so, does it make sense to make it an option for for the `frigidaire` library (as well as this one)? That way the more technical of us can use our own deviceId in the future by setting it in the homebridge config file.

**Comment by danielschwartz** [comment]
@karlg100 I got my mitmproxy running and i've got the `frigidaire` library working. I did some texting and i'm pretty sure the new header thats necessary is `X-WL-S-ClientId`, which is different than `X-WL-ClientId` and seems like it's something thats base64 encoded. Just so it's helpful here is the headers section of the code with my `X-WL-S-ClientId` added (and sanitized for obvious reasons):

```
var headers = {
        'x-wl-app-version': this.appVersion,
        'X-WL-Session': this.sessionId,
        'X-WL-ClientId': this.clientId,
        'X-Requested-With': 'XMLHttpRequest',
        'User-Agent': this.userAgent,
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'X-WL-ClientId': this.clientId,
        'X-WL-S-ClientId': 'XXXXXX'
}
```

**Comment by danielschwartz** [comment]
Upon some more testing, it seems like the API has changed. When I go to actually control the unit the library spits out a bunch of errors:

```
/homebridge/node_modules/frigidaire/lib/frigidaire.js:539
    err = new Error('Telementry not defined');
        ^
ReferenceError: err is not defined
    at Frigidaire.getValue (/homebridge/node_modules/frigidaire/lib/frigidaire.js:539:9)
    at Frigidaire.getUnit (/homebridge/node_modules/frigidaire/lib/frigidaire.js:615:8)
    at FrigidaireAirConditionerAccessory.getTemperatureDisplayUnits (/homebridge/node_modules/homebridge-frigidaire/index.js:191:13)
    at FrigidaireAirConditionerAccessory.updateAll (/homebridge/node_modules/homebridge-frigidaire/index.js:273:10)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-frigidaire/index.js:91:53)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```
Which then causes homebridge to start back up, and the kicks the library into an error loop with these errors: 
```
failed to parse json: '/*-secure-
{"challenges":{"XXXX":{"WL-Instance-Id":"XXXXX"}}}*/'

/homebridge/node_modules/frigidaire/lib/frigidaire.js:282
      return callback(null, body);
             ^
TypeError: Cannot read property 'attributes' of undefined
    at /homebridge/node_modules/frigidaire/lib/frigidaire.js:436:58
    at Request._callback (/homebridge/node_modules/frigidaire/lib/frigidaire.js:282:14)
    at Request.self.callback (/homebridge/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/homebridge/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
```

Hopefully this is helpful! I absolutely _hate_ the Frigidaire app, so would totally be happy to collaborate with you on a fix it's helpful.

**Comment by ntableman** [comment]
yeah I was able to use HomeKit to turn the ac on in a geofence and off when I left! I loved that. So annoying they made this change...but how is the old app still working if the old API is broken? Seems odd.

**Comment by danielschwartz** [comment]
@ntableman the API isn't broken, the API just changed and the underlying `frigidaire` library hasn't been updated to support it. If @karlg100 doesn't fix it, i'm sure i'll eventually get fed up enough with the app and try to fix it myself.

**Comment by ntableman** [comment]
@danielschwartz  semantics...if the api changes with out version control it means it is broken to the client. This is why most APIs have a version number in the URL, like Salesforce for a good example. I don't see that in this API so my comment was more asking how is the manufacturer rev'ing this somewhat rhetorically :) I assume they pushed out a new app (which still sucks).

I am busy with an ML and MQTT project or I'd dig in, but yeah if I get fed up enough I might take a crack at it.

**Comment by royale56** [comment]
The weather is starting to heat up and it would be awesome to get this working. Has anyone been able to find a fix?

**Comment by royale56** [comment]
Any new updates yet on this? I’d love to get it running with Siri again.

**Comment by royale56** [comment]
This issue appears to be fixed. Put my Frigidaire config back in and everything works as normal.

**Comment by danielschwartz** [comment]
This is not fixed for me. I still receive this error: 

```js
TypeError: Cannot read property 'attributes' of undefined
    at /homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:435:58
    at Request._callback (/homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:281:14)
    at Request.self.callback (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
```

@royale56 can you share your homebridge config (minus sensitive info) to see if theres something we are all screwing up config wise?

**Comment by royale56** [comment]
Before I added my Frigidaire config back in I ran sudo npm install -g homebridge-frigidaire just incase something got messed up but my config is actually a copy and paste of what’s in the readme. Have you changed anything in your Frigidaire.js?

Let me know if you have any luck getting it to work after running the command again.

**Comment by danielschwartz** [comment]
Nothing changed on my end. I also tried deleting and recreating the docker container running my homebridge server and I still see the above issue 😕

**Comment by karlg100** [comment]
I just reinstalled from the npm release, restored my config, and so far no 403 errors.  devices discovered, online and working.

Is anyone still experiencing this?

**Comment by danielschwartz** [comment]
Working for me again now! Not sure what changed but when I started my homebridge docker container up this afternoon everything just worked 😄

**Comment by karlg100** [comment]
sounds good. going to close for now.

**Comment by karlg100** [comment]
I will also say, everyone should update. the polling interval is messed up.  update to the latest.  this may have been the cause - too many queries and they may have blocked the client ID in the Homebridge library.
